apiVersion: v1
kind: Service
metadata:
  name: pmm-server
spec:
  ports:
    - port: 80
  selector:
    app: pmm
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 80Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pmm
  labels:
    app: pmm
spec:
  selector:
    matchLabels:
      app: pmm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pmm
    spec:
      containers:
      - name: pmm
        image: percona/pmm-server
        ports:
        - containerPort: 80
          name: pmm
        resources:
          requests:
            cpu: 200m
            memory: 3Gi
        volumeMounts:
        - mountPath: "/opt/prometheus/data"
          name: data
          subPath: prometheus
        - mountPath: "/opt/consul-data"
          name: data
          subPath: consul
        - mountPath: "/var/lib/grafana"
          name: data
          subPath: grafana
        - mountPath: "/var/lib/mysql"
          name: data
          subPath: mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
